import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const KEY = 'kk_lang'
const LanguageContext = createContext(null)

const COPY = {
  bn: {
    todayPaper: 'আজকের পত্রিকা',
    epaper: 'ই-পেপার',
    magazine: 'ম্যাগাজিন',
    social: 'সোশ্যাল মিডিয়া',
    login: 'লগইন',
    search: 'খুঁজুন...',
    home: 'প্রচ্ছদ',
    categories: 'ক্যাটাগরি',
    importantLinks: 'গুরুত্বপূর্ণ লিংক',
    contact: 'যোগাযোগ',
    newsStories: 'নিউজ স্টোরিজ',
    discussed: 'আলোচিত',
    related: 'সম্পর্কিত খবর',
    moreNews: 'আরও খবর',
    views: 'ভিউ',
    loading: 'লোড হচ্ছে...',
    all: 'সব',
    searchPage: 'খোঁজ',
    searchBtn: 'খুঁজুন',
    noEnglish: 'ইংরেজি ভার্সন নেই — বাংলা দেখানো হচ্ছে',
    backTop: 'উপরে যান',
    adminPanel: 'অ্যাডমিন প্যানেল',
    adminLoading: 'অ্যাডমিন প্যানেল লোড হচ্ছে...',
    viewSite: 'সাইট দেখুন',
    logout: 'লগআউট',
    menu: 'মেনু',
    navMain: 'মূল',
    navContent: 'কন্টেন্ট',
    navGallery: 'গ্যালারি',
    navStaffSec: 'স্টাফ ও রাইটার',
    navSettings: 'সেটিংস',
    navDashboard: 'ড্যাশবোর্ড',
    navCategories: 'ক্যাটাগরি',
    navSubcategories: 'সাবক্যাটাগরি',
    navNewPost: 'পোস্ট যোগ',
    navAllPosts: 'সব পোস্ট',
    navHomeLead: 'হোম নিউজ পজিশন',
    navPhotos: 'ফটো গ্যালারি',
    navVideos: 'ভিডিও গ্যালারি',
    navStaff: 'স্টাফ',
    navWriters: 'রাইটার',
    navPassword: 'পাসওয়ার্ড',
    navWebsite: 'ওয়েবসাইট সেটিং',
    navNamaz: 'নামাজের সময়',
    navNotice: 'নোটিশ',
    navSocial: 'সোশ্যাল মিডিয়া',
    navSeo: 'এসইও',
    navAds: 'বিজ্ঞাপন / অ্যাডস',
    navWebsites: 'গুরুত্বপূর্ণ ওয়েবসাইট',
    loginAdmin: 'কৃষিকাগজ অ্যাডমিন',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    loggingIn: 'লগইন হচ্ছে...',
    reporterReg: 'রিপোর্টার রেজিস্ট্রেশন',
    greetMorning: 'শুভ সকাল',
    greetAfternoon: 'শুভ বিকেল',
    greetEvening: 'শুভ সন্ধ্যা',
    totalPosts: 'মোট পোস্ট',
    published: 'প্রকাশিত',
    totalViews: 'মোট ভিউ',
    viewsSum: 'সব খবরের যোগফল',
    todayPosts: 'আজকের পোস্ট',
    in7days: '৭ দিনে',
    drafts: 'ড্রাফট',
    pendingWriters: 'অপেক্ষমাণ রাইটার',
    headlines: 'হেডলাইন',
    featured: 'ফিচার্ড',
    popular: 'জনপ্রিয়',
    photos: 'ফটো',
    videos: 'ভিডিও',
    staff: 'স্টাফ',
    writers: 'রাইটার',
    websites: 'ওয়েবসাইট',
    newPost: 'নতুন পোস্ট',
    newPostDesc: 'খবর লিখুন ও প্রকাশ করুন',
    allPostsDesc: 'তালিকা দেখুন ও সম্পাদনা',
    homeLeadDesc: 'ড্র্যাগ করে খবরের জায়গা বদলান',
    catDesc: 'বিভাগ ম্যানেজ করুন',
    photoDesc: 'ছবি আপলোড/সম্পাদনা',
    videoDesc: 'ভিডিও গ্যালারি',
    siteDesc: 'নাম, লোগো, যোগাযোগ',
    writerDesc: 'অ্যাকাউন্ট অনুমোদন',
    siteLiveDesc: 'লাইভ পোর্টাল খুলুন',
    homeLeadTitle: 'হোম নিউজ পজিশন',
    homeLeadHelp: 'খবর টেনে বসান, অথবা বেছে নিন বাটনে ক্লিক করে খবর সিলেক্ট করুন। সেভ করলে সাইটে সেই জায়গায়ই দেখাবে।',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে...',
    deleteAll: 'সব ডিলিট',
    delete: 'ডিলিট',
  },
  en: {
    todayPaper: "Today's paper",
    epaper: 'E-paper',
    magazine: 'Magazine',
    social: 'Social media',
    login: 'Login',
    search: 'Search...',
    home: 'Home',
    categories: 'Categories',
    importantLinks: 'Important links',
    contact: 'Contact',
    newsStories: 'News stories',
    discussed: 'Trending',
    related: 'Related news',
    moreNews: 'More news',
    views: 'views',
    loading: 'Loading...',
    all: 'All',
    searchPage: 'Search',
    searchBtn: 'Search',
    noEnglish: 'English version not available — showing Bangla',
    backTop: 'Back to top',
    adminPanel: 'Admin panel',
    adminLoading: 'Loading admin panel...',
    viewSite: 'View site',
    logout: 'Logout',
    menu: 'Menu',
    navMain: 'Main',
    navContent: 'Content',
    navGallery: 'Gallery',
    navStaffSec: 'Staff & writers',
    navSettings: 'Settings',
    navDashboard: 'Dashboard',
    navCategories: 'Categories',
    navSubcategories: 'Subcategories',
    navNewPost: 'Add post',
    navAllPosts: 'All posts',
    navHomeLead: 'Home news positions',
    navPhotos: 'Photo gallery',
    navVideos: 'Video gallery',
    navStaff: 'Staff',
    navWriters: 'Writers',
    navPassword: 'Password',
    navWebsite: 'Website settings',
    navNamaz: 'Prayer times',
    navNotice: 'Notice',
    navSocial: 'Social media',
    navSeo: 'SEO',
    navAds: 'Ads / promotions',
    navWebsites: 'Important websites',
    loginAdmin: 'Krishikagos Admin',
    email: 'Email',
    password: 'Password',
    loggingIn: 'Signing in...',
    reporterReg: 'Reporter registration',
    greetMorning: 'Good morning',
    greetAfternoon: 'Good afternoon',
    greetEvening: 'Good evening',
    totalPosts: 'Total posts',
    published: 'published',
    totalViews: 'Total views',
    viewsSum: 'Sum of all news views',
    todayPosts: "Today's posts",
    in7days: 'in 7 days',
    drafts: 'Drafts',
    pendingWriters: 'pending writers',
    headlines: 'Headlines',
    featured: 'Featured',
    popular: 'Popular',
    photos: 'Photos',
    videos: 'Videos',
    staff: 'Staff',
    writers: 'Writers',
    websites: 'Websites',
    newPost: 'New post',
    newPostDesc: 'Write and publish news',
    allPostsDesc: 'List and edit posts',
    homeLeadDesc: 'Drag news into homepage slots',
    catDesc: 'Manage sections',
    photoDesc: 'Upload / edit photos',
    videoDesc: 'Video gallery',
    siteDesc: 'Name, logo, contact',
    writerDesc: 'Approve accounts',
    siteLiveDesc: 'Open live portal',
    homeLeadTitle: 'Home news positions',
    homeLeadHelp: 'Drag news into slots, or click Choose to pick from the list. After save they appear in those places on the site.',
    save: 'Save',
    saving: 'Saving...',
    deleteAll: 'Delete all',
    delete: 'Delete',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try {
      const saved = localStorage.getItem(KEY)
      if (saved === 'en' || saved === 'bn') return saved
    } catch {
      /* ignore */
    }
    return 'bn'
  })

  useEffect(() => {
    document.documentElement.lang = lang === 'en' ? 'en' : 'bn'
    try {
      localStorage.setItem(KEY, lang)
    } catch {
      /* ignore */
    }
  }, [lang])

  const value = useMemo(() => {
    const isEn = lang === 'en'
    return {
      lang,
      isEn,
      t: COPY[lang],
      setLang: setLangState,
      toggleLang: () => setLangState((v) => (v === 'en' ? 'bn' : 'en')),
      text: (bn, en) => (isEn && en ? en : bn),
    }
  }, [lang])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLang() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLang must be used within LanguageProvider')
  return ctx
}
